- targets:
    - http://www.google.com/;google.com
    - https://github.com/;github.com
    - https://www.apple.com/;apple.com
    - https://www.expedia.com/;expedia.com
    - http://192.168.22.1:8833/ss/;Firewalla_Gateway
